name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22.x"
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"
    - shell: bash
      run: pnpm audit
    - shell: bash
      run: pnpm install
    - shell: bash
      run: pnpm ls -r --depth 0
      name: "List packages"
