packages:
  - packages/*
  - apps/*

auditConfig:
  ignoreGhsas:
    - GHSA-mh29-5h37-fv8m

overrides:
  expr-eval-fork@<=2.0.2: '>=3.0.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
