packages:
  - packages/*
  - apps/*

autoInstallPeers: false

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - "@isaacs/brace-expansion@5.0.1"
  - ts-api-utils@2.4.0

overrides:
  "@isaacs/brace-expansion@<=5.0.0": ">=5.0.1"
  glob@>=10.0.0 <11.1.0: ">=11.1.0"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  qs@<=6.14.1: ">=6.14.2"

trustPolicy: no-downgrade

trustPolicyExclude:
  - rxjs@7.8.2
  - semver@6.3.1

auditConfig:
  ignoreGhsas:
    - GHSA-2g4f-4pwh-qvx6
