packages:
  - packages/*
  - apps/*
  - tools/*

allowBuilds:
  esbuild: false

autoInstallPeers: false

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.4.6'
  - '@storybook/addon-docs@10.4.6'
  - '@storybook/addon-vitest@10.4.6'
  - '@storybook/builder-vite@10.4.6'
  - '@storybook/csf-plugin@10.4.6'
  - '@storybook/react-dom-shim@10.4.6'
  - '@storybook/react-vite@10.4.6'
  - '@storybook/react@10.4.6'
  - eslint-plugin-storybook@10.4.6
  - esbuild@0.28.1
  - js-yaml@4.1.2
  - shell-quote@1.8.4

overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@<=4.1.1: ^4.1.2
  shell-quote@>=1.1.0 <=1.8.3: ^1.8.4

trustPolicy: no-downgrade

trustPolicyExclude:
  - rxjs@7.8.2
  - semver@6.3.1
