packages:
  - packages/*
  - apps/*

overrides:
  expr-eval-fork@<=2.0.2: ">=3.0.0"

auditConfig:
  ignoreGhsas:
    # fix backported to 3.14.2, but security advisory is not updated
    # https://github.com/nodeca/js-yaml/pull/731
    - GHSA-mh29-5h37-fv8m
