// this separate barrel file allows us to avoid circular dependencies
// components could import from @digdir/designsystemet-react directly,
//  but we want to ensure internal use aligns with exported components and eventual overrides

export type * from "@digdir/designsystemet-react";

// use named re-exports instead of export * to fix error with RSC:
// "It's currently unsupported to use "export *" in a client boundary. Please use named exports instead."
//
// NB: Storybook generates a docgen wrapper per component in this list so autodocs
// show real prop types (see docs/adr/adr-0004-storybook-docgen-wrappers.md).
// After adding a component here, run `pnpm --filter @arbeidstilsynet/storybook
// gen:docgen-wrappers`. A vitest test fails if the wrappers are stale.
export {
  Alert,
  Avatar,
  Badge,
  BadgePosition,
  Breadcrumbs,
  BreadcrumbsItem,
  BreadcrumbsLink,
  BreadcrumbsList,
  Button,
  Card,
  CardBlock,
  Checkbox,
  Chip,
  ChipButton,
  ChipCheckbox,
  ChipRadio,
  ChipRemovable,
  Combobox,
  ComboboxEmpty,
  ComboboxOption,
  Details,
  DetailsContent,
  DetailsSummary,
  Dialog,
  DialogBlock,
  DialogTrigger,
  DialogTriggerContext,
  Divider,
  Dropdown,
  DropdownButton,
  DropdownHeading,
  DropdownItem,
  DropdownList,
  DropdownTrigger,
  DropdownTriggerContext,
  EXPERIMENTAL_AvatarStack,
  EXPERIMENTAL_Suggestion,
  EXPERIMENTAL_SuggestionClear,
  EXPERIMENTAL_SuggestionEmpty,
  EXPERIMENTAL_SuggestionInput,
  EXPERIMENTAL_SuggestionList,
  EXPERIMENTAL_SuggestionOption,
  ErrorSummary,
  ErrorSummaryHeading,
  ErrorSummaryItem,
  ErrorSummaryLink,
  ErrorSummaryList,
  Field,
  FieldAffix,
  FieldAffixes,
  FieldCounter,
  FieldDescription,
  Fieldset,
  FieldsetDescription,
  FieldsetLegend,
  Heading,
  Input,
  Label,
  Link,
  List,
  ListItem,
  ListOrdered,
  ListUnordered,
  Pagination,
  PaginationButton,
  PaginationItem,
  PaginationList,
  Paragraph,
  Popover,
  PopoverTrigger,
  PopoverTriggerContext,
  Radio,
  RovingFocusItem,
  RovingFocusRoot,
  Search,
  SearchButton,
  SearchClear,
  SearchInput,
  Select,
  SelectOptgroup,
  SelectOption,
  Skeleton,
  SkipLink,
  Spinner,
  Switch,
  Table,
  TableBody,
  TableCell,
  TableFoot,
  TableHead,
  TableHeaderCell,
  TableRow,
  Tabs,
  TabsList,
  TabsPanel,
  TabsTab,
  Tag,
  Textarea,
  Textfield,
  ToggleGroup,
  ToggleGroupItem,
  Tooltip,
  ValidationMessage,
  omit,
  useCheckboxGroup,
  useDebounceCallback,
  useIsomorphicLayoutEffect,
  useMediaQuery,
  usePagination,
  useRadioGroup,
  useSynchronizedAnimation,
} from "@digdir/designsystemet-react";
