name: Audit

on:
  pull_request:

jobs:
  audit:
    name: Audit dependencies
    if: github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          install: false
      - run: pnpm audit
