## Based on https://github.com/scaleway/ultraviolet/blob/7ba5ded00462e30d5a37de90c06be49640786849/.github/workflows/changesets-renovate.yml

name: Generate changeset for Renovate

on:
  pull_request_target:
    paths:
      - ".github/workflows/changesets-renovate.yml"
      - "**/pnpm-lock.yaml"
      - "**/package.json"

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'Arbeidstilsynet/design'
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: ${{ vars.BETZY_BOT_APP_ID }}
          private-key: ${{ secrets.BETZY_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 10
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Set git user
        run: |
          git config --global user.name "${{ vars.BETZY_BOT_GIT_USER_NAME }}"
          git config --global user.email "${{ vars.BETZY_BOT_GIT_USER_EMAIL }}"

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
