name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prek:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2

  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@72d8b6a4a6492697599795caf6bf6d3862474946 # v1
      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@72d8b6a4a6492697599795caf6bf6d3862474946 # v1
      - run: pnpm build

  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@72d8b6a4a6492697599795caf6bf6d3862474946 # v1
      - run: pnpm lint
      - run: pnpm test
        id: test

      - name: "Report Coverage"
        if: steps.test.outcome == 'success' || steps.test.outcome == 'failure'
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2
        # known issue: status check will be attached to the wrong workflow
        # https://github.com/orgs/community/discussions/24616
        # https://github.com/EnricoMi/publish-unit-test-result-action/issues/12
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2
        if: steps.test.outcome == 'success' || steps.test.outcome == 'failure'
        with:
          files: "test-report.xml"

  storybook-tests:
    name: Storybook Tests
    uses: ./.github/workflows/storybook-tests.yml
