name: Deploy Storybook to Nais (reusable)

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      vars:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker
        with:
          team: plattform
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/storybook.yml
          WORKLOAD_IMAGE: ${{ steps.docker.outputs.image }}
          VARS: ${{ inputs.vars }}
