name: Deploy Storybook to Nais (reusable)

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      vars:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0 # v0
        id: docker
        with:
          team: plattform
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/storybook.yml
          WORKLOAD_IMAGE: ${{ steps.docker.outputs.image }}
          VARS: ${{ inputs.vars }}
