name: Generate CSS from Figma tokens

on:
  push:
    branches-ignore:
      - "main"
      - "renovate/**"
      - "changeset-release/**"
    paths:
      - "design-tokens/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-css:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@f6af8754b7e046f209b2f001f7a71c06b9ab4381 # v1

      - name: Generate CSS
        run: pnpm tokens:build

      - name: Commit changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          pull: "--rebase --autostash"
          default_author: github_actions
          message: "Generated theme CSS"
          add: "."
