name: Storybook tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./apps/storybook
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: Arbeidstilsynet/action-pnpm-setup@444e7145c433049678332616ef8f5b076c2dec8b # v4
      - run: pnpm exec playwright install
      - name: Build CSS
        run: pnpm --filter @arbeidstilsynet/design-css build
      - run: pnpm test
